services:
  app:
    build:
      context: ../../FastAPI-bot-backend/
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    restart: unless-stopped
    expose:
      - 8000
    environment:
      MONGO_DB_CONNECTION_URI: "mongodb://mongodb:27017"
      KAFKA_URL: "kafka:29092"
      MONGO_DB_ADMIN_USERNAME: "admin"
      MONGO_DB_ADMIN_PASSWORD: "admin"
    volumes:
      - ../../FastAPI-bot-backend:/FastAPI-bot-backend
    command: ["python", "-Om", "src"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
