services:
  mongodb-backup:
    container_name: mongodb-backup
    image: mongo:6-jammy
    restart: always
    volumes:
      - db_backup:/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
    entrypoint: ["/bin/bash", "-c", "echo '*/5 * * * 5 root /usr/bin/mongodump --uri=mongodb://mongodb:27017 --out=/backup/$(date +\\%F)' >> /etc/crontab && cron -f"]
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  db_backup:

networks:
  backend:
    driver: bridge